#!/usr/bin/env bash
# scripts/backup.sh: back up the Immich stack into a private (0700) directory.
#
#   scripts/backup.sh [--dest DIR] [--cold] [--full] [--no-library]
#
#   (default)      hot backup while Immich runs:
#                    immich-db.sql.gz  pg_dumpall --clean --if-exists (Immich's own method)
#                    library.tgz       the library without thumbs/ and encoded-video/
#                                      (both are regenerated by Immich)
#                    secrets/immich-db-password (0600), immich.env, units/, images.txt,
#                    SHA256SUMS
#   --full         also archive thumbs/ and encoded-video/
#   --no-library   skip library.tgz (for a large library backed up by other means)
#   --cold         also stop immich.target and archive the PostgreSQL directory byte for
#                  byte (podman unshare tar: it belongs to a container subuid), then start again
#   --dest DIR     default ~/backups/immich/<YYYYmmdd-HHMMSS>
#
# scripts/restore.sh <DIR> puts a backup back. Keep copies off this host.
# shellcheck source-path=SCRIPTDIR
set -euo pipefail
REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
# shellcheck source=lib/quadlet-lib.sh
. "$REPO/scripts/lib/quadlet-lib.sh"
# shellcheck source=app.sh
. "$REPO/scripts/app.sh"

dest='' cold=0 full=0 no_library=0
while (($#)); do
  case $1 in
    --dest) dest=${2:?--dest needs a directory}; shift ;;
    --cold) cold=1 ;;
    --full) full=1 ;;
    --no-library) no_library=1 ;;
    -h | --help) sed -n '2,19p' "$0"; exit 0 ;;
    *) ql_die "unknown option $1 (see --help)" ;;
  esac
  shift
done
ql_require_rootless
ql_lock "$APP"
ql_env_load "$ENV_FILE"
app_running "$DB_CONTAINER" || ql_die "$DB_CONTAINER is not running (start it: systemctl --user start $TARGET)"
library_dir=$(app_dir HOST_LIBRARY_DIR)
postgres_dir=$(app_dir HOST_POSTGRES_DIR)

dest=$(app_new_backup_dir "$dest")
ql_info "backing up $APP to $dest"

# ---- hot part ----------------------------------------------------------------------------
app_dump_db "$dest/immich-db.sql.gz"
mkdir -p "$dest/secrets"
if podman secret exists "$SECRET_DB"; then app_save_secret "$SECRET_DB" "$dest/secrets/$SECRET_DB"; fi
[[ ! -f $ENV_FILE ]] || cp -p -- "$ENV_FILE" "$dest/"
if app_is_installed; then app_snapshot_units "$dest/units"; fi
{
  printf 'immich version: %s\n' "$(app_api_version)"
  printf 'library: %s\npostgres: %s\n' "$library_dir" "$postgres_dir"
  podman ps -a --filter label=io.woowtech.app=immich --format '{{.Names}} {{.ImageName}} {{.ImageID}}' 2>/dev/null || true
} >"$dest/images.txt"

if ((!no_library)); then
  ex=()
  ((full)) || ex=(--exclude 'library/thumbs' --exclude 'library/encoded-video')
  ql_backup_dir "$library_dir" "$dest/library.tgz" "${ex[@]}" >/dev/null
fi

# ---- cold part: PGDATA as bytes, with the whole stack stopped -------------------------------
# restart_target: bring $TARGET back if this script ends between the stop and the start below.
# A hook, not `trap ... EXIT`, which would replace the handler ql_lock armed.
restart_target() { ((restart)) || return 0; systemctl --user start "$TARGET" || ql_warn "could not restart $TARGET"; }
if ((cold)); then
  mapfile -t units < <(app_units)
  restart=0
  ql_cleanup restart restart_target
  ql_info "stopping $TARGET for the cold copy of the database directory"
  restart=1
  systemctl --user stop "${units[@]}"
  ql_backup_dir "$postgres_dir" "$dest/postgres-dir.tgz" >/dev/null
  systemctl --user start "$TARGET"
  # shellcheck disable=SC2034 # read by the restart_target cleanup hook
  restart=0
fi

app_write_checksums "$dest"
ql_info "backup complete: $dest ($(du -sh -- "$dest" | cut -f1))"
printf '%s\n' "$dest"
